// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suszrnpkeseixlhohzeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1c3pybnBrZXNlaXhsaG9oemV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzk2NjQsImV4cCI6MjA2OTY1NTY2NH0.4v5h1Ko9ebBGQl8CSTtE-DRYfVpHXSFgBq1OkAAYDhc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});